config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :account, only: %i[show edit update]
    resources :custom_attributes
    resources :users
    resources :resources
    resources :schedule_categories
  end

  resources :bookings do
    collection do
      post :check
    end
  end

  resource :session
  resources :passwords, param: :token
  resources :calendar, only: %i[index new create] do
    collection do
      post :check
    end
  end
  resources :calendar_events, only: %i[index]

  root to: "calendar#index"
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :find_date
  before_action :find_schedule_categories, only: %i[new create]
  before_action :find_resources, only: %i[new create]

  def index
    monthly_info = Bookings::Calendar.call Current.account, @date.strftime("%Y-%m")
    @weeks = monthly_info.each_slice(7).to_a
    @total_weeks = @weeks.size
    @current_week_index = current_week_index
  end

  def new
    @booking = Current.user.bookings.new start_on: booking_date, schedule_category_id: @schedule_categories.first[0]
    available_resources
    current_info
    custom_attributes
  end

  def create
    if Current.user.admin? && params[:booking][:blocked] == "1"
      @booking = Bookings::BlockSchedule.new(Current.user, params[:booking][:start_on], params[:booking][:schedule_category_id]).call
      flash.now[:notice] = t("bookings.blocked_created")
      @day = {
        day: @booking.start_on,
        bookings: bookings_for_day
      }
      build_weekly_data
    else
      @booking = Current.user.bookings.create booking_params

      if @booking.persisted?
        Bookings::BookingCustomAttributes.new(@booking, params[:custom_attribute_ids], Current.account).create
        flash.now[:notice] = t("bookings.created")
        @day = {
          day: @booking.start_on,
          bookings: bookings_for_day
        }
        build_weekly_data
      else
        available_resources
        current_info
        custom_attributes
      end
    end
  end

  def check
    available_resources
    current_info
    custom_attributes
  end

  private

    def build_weekly_data
      @date = @booking.start_on
      monthly_info = Bookings::Calendar.call Current.account, @date.strftime("%Y-%m")
      @weeks = monthly_info.each_slice(7).to_a
      @total_weeks = @weeks.size
      @current_week_index = current_week_index
    end

    def booking_params
      params.require(:booking).permit(:start_on, :schedule_category_id, :participants, resource_bookings_attributes: %i[resource_id])
    end

    def find_date
      @date = if params[:date].blank?
        Date.current
      else
        Date.parse(params[:date])
      end
    end

    def custom_attributes
      @custom_attributes = Bookings::CustomAttributes.new(Current.user, start_on, schedule_category_id).call
    end

    def find_schedule_categories
      @schedule_categories = Current.account.schedule_categories.pluck(:id, :name)
    end

    def find_resources
      @resources = Current.account.resources
        .includes(:resource_bookings).order(max_capacity: :desc)
    end

    def start_on
      return @booking.start_on if params[:booking].blank? || params[:booking][:start_on].blank?

      params[:booking][:start_on]
    end

    def schedule_category_id
      return @booking.schedule_category_id if params[:booking].blank? || params[:booking][:schedule_category_id].blank?

      params[:booking][:schedule_category_id]
    end

    def available_resources
      @available_resources, @errors = Bookings::AvailableResources.new(Current.user, start_on, schedule_category_id).call
    end

    def current_info
      info = Bookings::CurrentInfo.new(Current.account, start_on, schedule_category_id).call

      @num_bookings = info[:num_bookings]
      @participants = info[:participants]
      @schedule_name = info[:schedule_name]
      @schedule_blocked = info[:blocked]
    end

    def bookings_for_day
      Current.account.bookings
                  .for_today(start_on)
                  .group(:start_on, :schedule_category_id)
                  .select("bookings.start_on, sum(bookings.participants) as participants, schedule_categories.name as schedule_category_name, schedule_categories.colour as schedule_category_colour, MAX(CASE WHEN bookings.blocked = 1 THEN 1 ELSE 0 END) as schedule_blocked")
    end

    def current_week_index
      target = (@date.month == Date.current.month && @date.year == Date.current.year) ? Date.current : @date.beginning_of_month
      @weeks.each_with_index do |week, i|
        return i if week.any? { |day| day[:day] == target }
      end
      0
    end

    def booking_date
      return Date.current if params[:date].blank?

      Date.parse params[:date]
    rescue
      Date.current
    end
end

app/views/calendar/_large_calendar.html.haml
.flex.bg-gray-200.text-xs.leading-6.text-gray-700.lg:flex-auto
  .hidden.w-full.lg:grid.lg:grid-cols-7.lg:gap-px{class: "lg:grid-rows-#{@weeks.size}"}
    = render partial: 'large_week_row', collection: @weeks, as: :week_row
/ grid-rows-4
/ grid-rows-5
/ grid-rows-6

app/views/calendar/_large_day.html.haml
%div{id: day[:day]}
  %div{class: "relative py-2 px-3 min-h-24 hover:bg-stone-200 #{day[:day] == Date.current ? "bg-blue-100" : "bg-stone-50 text-gray-500"}"}
    - if day[:day].past?
      .flex.justify-between.items-center
        %time{class: "#{"flex h-6 w-6 items-center justify-center rounded-full bg-indigo-600 font-semibold text-white" if day[:day] == Date.current}", datetime: "#{day.to_s}"}
          = day[:day].strftime('%d')
      %ol.mt-2
        = render partial: 'calendar/large_show_event', collection: day[:bookings], as: :result
    - else
      = link_to new_calendar_path(date: day[:day]), data: {turbo_frame: 'modal'} do
        .absolute.h-full.w-full
          .flex.justify-between
            %time{class: "#{"flex h-6 w-6 items-center justify-center rounded-full bg-indigo-600 font-semibold text-white" if day[:day] == Date.current}", datetime: "#{day.to_s}"}
              = day[:day].strftime('%d')
          %ol.relative.mt-2
            = render partial: 'calendar/large_show_event', collection: day[:bookings], as: :result

app/views/calendar/_large_show_event.html.haml
= render partial: "shared/booking_card", locals: {schedule_category_name: result.schedule_category_name, schedule_category_colour: result.schedule_category_colour, participants: result.participants, schedule_blocked: result.schedule_blocked}

app/views/calendar/_large_week_row.html.haml
= render partial: 'large_day', collection: week_row, as: :day

app/views/calendar/_mid_calendar.html.haml
.isolate.grid.w-full.grid-cols-7.gap-1.lg:hidden{class: "grid-rows-#{@weeks.size}"}
  = render partial: 'mid_week_row', collection: @weeks, as: :week_row

app/views/calendar/_mid_day.html.haml
- total_results = day[:bookings].presence || []
%div{id: "mid_#{day[:day]}", class: "flex h-14 flex-col bg-stone-50 hover:bg-gray-100 focus:z-10 #{ day[:day] == Date.current ? "text-indigo-600 font-semibold " : "text-gray-500 " }"}
  %time{class: "ml-auto #{ day[:day] == Date.current ? "mt-1 flex mr-1 h-6 w-6 items-center text-white justify-center rounded-full bg-indigo-600 " : "flex h-6 w-6 pr-1 items-center text-gray-400 justify-center rounded-full " }"}
    = day[:day].strftime('%d')
  = link_to calendar_events_url(date: day[:day]), data: { turbo_frame: 'calendar_events_mid' }, class: "px-2 flex gap-1 justify-center" do
    - if total_results.any?
      = render partial: 'mid_show_event', collection: total_results, as: :result

app/views/calendar/_mid_show_event.html.haml
- if result.schedule_blocked.to_i == 1
  %span.text-sm.text-center.text-red-800.font-bold
    x
- else
  %span.text-sm.text-center{class: "text-#{result.schedule_category_colour}-800"}
    o

app/views/calendar/_mid_week_row.html.haml
= render partial: 'mid_day', collection: week_row, as: :day

app/views/calendar/_weekly_bookings.html.haml
#weekly_bookings
  .lg:hidden.mt-4.overflow-hidden.rounded-lg.bg-white.shadow{"data-controller" => "week-navigation", "data-week-navigation-current-value" => @current_week_index, "data-week-navigation-total-value" => @total_weeks}
    .flex.items-center.justify-between.px-4.py-2
      %button.p-2.text-gray-600.hover:text-gray-900{"data-action" => "week-navigation#previous"}
        = image_tag 'icons/left_arrow.svg', class: "w-5 h-5"
      %span.text-sm.font-medium.text-gray-700{"data-week-navigation-target" => "label"}
        = "#{t('calendar.weekly.week')} #{@current_week_index + 1} de #{@total_weeks}"
      %button.p-2.text-gray-600.hover:text-gray-900{"data-action" => "week-navigation#next"}
        = image_tag 'icons/right_arrow.svg', class: "w-5 h-5"
    - @weeks.each do |week|
      .hidden{"data-week-navigation-target" => "week"}
        = render partial: 'calendar/weekly_day_list', locals: { week: week }

app/views/calendar/_weekly_day_list.html.haml
- days_with_bookings = week.select { |day| day[:bookings].present? }
- if days_with_bookings.empty?
  .px-4.py-6.text-center.text-sm.text-gray-500
    = t('calendar.weekly.no_bookings')
- else
  .divide-y.divide-gray-100
    - days_with_bookings.each do |day|
      .px-4.py-3
        %h4.text-sm.font-semibold.text-gray-900.capitalize
          = l(day[:day], format: :day_name_number)
        %ol.mt-1.space-y-1
          - day[:bookings].each do |result|
            = render partial: "shared/booking_card", locals: { schedule_category_name: result.schedule_category_name, schedule_category_colour: result.schedule_category_colour, participants: result.participants, schedule_blocked: result.schedule_blocked }

app/views/calendar/create.turbo_stream.haml
- if @booking.valid?
  = turbo_stream.update 'modal' do
    %div
  = turbo_stream.replace 'flash-messages' do
    = render Notifications::FlashComponent.new(flash)
  = turbo_stream.replace @day[:day] do
    = render 'calendar/large_day', day: @day
  = turbo_stream.replace "mid_#{@day[:day]}" do
    = render 'calendar/mid_day', day: @day
  = turbo_stream.replace 'weekly_bookings' do
    = render 'calendar/weekly_bookings'
- else
  = turbo_stream.update 'modal_content' do
    = tw_form_with model: @booking, url: calendar_index_path, data: { turbo: true, controller: :booking, booking_resources_value: resources_for_frontend(@available_resources).as_json, booking_capacity_value: capacity_for_frontend(@available_resources), booking_translations_value: translations_for_frontend.to_json } do |form|
      = render 'bookings/form', booking: @booking, f: form

app/views/calendar/index.html.haml
.divide-y.divide-gray-200.overflow-hidden.rounded-lg.bg-white.shadow
  .px-4.py-5.sm:px-6
    .flex.items-center.justify-between.gap-4
      .flex-1
      .flex.items-center
        .w-6.mr-3
          = link_to calendar_index_path(date: @date - 1.month), class: "w-5 h-5" do
            = image_tag 'icons/left_arrow.svg'
        %h2.flex.items-center.text-2xl.font-bold.leading-7.text-neutral-800.sm:text-3xl.sm:leading-9.sm:truncate
          = (l @date, format: :month_year)
        .w-6.ml-3
          = link_to calendar_index_path(date: @date + 1.month), class: "w-5 h-5" do
            = image_tag 'icons/right_arrow.svg'
      .flex-1.flex.justify-end
        = render 'shared/button_new', destination: new_calendar_path(date: Date.current), title: t('bookings.newTitle'), data: { turbo_frame: 'modal' }
.px-4.py-5.sm:p-6
  .mt-2.shadow.lg:flex.lg:flex-auto.lg:flex-col
    .grid.grid-cols-7.gap-px.border-b.border-gray-300.bg-gray-200.text-center.text-xs.font-semibold.leading-6.text-gray-700.lg:flex-none
      .bg-white.py-2
        = t 'calendar.monday.long'
      .bg-white.py-2
        = t 'calendar.tuesday.long'
      .bg-white.py-2
        = t 'calendar.wednesday.long'
      .bg-white.py-2
        = t 'calendar.thursday.long'
      .bg-white.py-2
        = t 'calendar.friday.long'
      .bg-white.py-2
        = t 'calendar.saturday.long'
      .bg-white.py-2
        = t 'calendar.sunday.long'
    = render 'calendar/large_calendar'
    = render 'calendar/mid_calendar'
  %ol.mt-4.divide-y.divide-gray-100.overflow-hidden.rounded-lg.bg-white.text-sm.lg:mt-10
    = turbo_frame_tag 'calendar_events_mid'
  = render 'calendar/weekly_bookings'

app/views/calendar/new.html.haml
= render 'shared/modal', title: t('bookings.newTitle') do
  = tw_form_with model: @booking, url: calendar_index_path, data: { turbo: true, controller: :booking, booking_resources_value: resources_for_frontend(@available_resources).as_json, booking_capacity_value: capacity_for_frontend(@available_resources), booking_translations_value: translations_for_frontend.to_json } do |form|
    = render 'bookings/form', booking: @booking, f: form