config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :account, only: %i[show edit update]
    resources :custom_attributes
    resources :users
    resources :resources
    resources :schedule_categories
  end

  resources :bookings do
    collection do
      post :check
    end
  end

  resource :session
  resources :passwords, param: :token
  resources :calendar, only: %i[index new create] do
    collection do
      post :check
    end
  end
  resources :calendar_events, only: %i[index]

  root to: "calendar#index"
end

app/views/admin/resources/_form.html.haml
= render 'shared/form_card', title: t('admin.resources.title') do
  = tw_form_with model: [:admin, resource] do |form|
    = render 'shared/form_errors', errors: resource.errors
    .space-y-1
      = form.text_input :name
      = form.number_input :max_capacity
      = form.file_input :photo
    = render 'shared/form_actions', cancel_url: admin_resources_path

app/views/admin/resources/_resource.html.haml
%tr
  %td{class: td_class.render}
    = image_tag resource_image(resource), class: 'h-10 w-10 rounded'
  %td{class: td_class.render}
    = link_to bookings_path(resource_id: resource.id), class: link_class.render do
      = resource.name
  %td{class: td_class.render(text_align: :right)}
    = resource.max_capacity
  %td{class: td_class.render}
    .flex.gap-x-4.justify-end
      = render 'shared/button_edit', destination: edit_admin_resource_path(resource), data: { target: "_top" }
      = render 'shared/button_delete', destination: {model: [:admin, resource]}

app/views/admin/resources/edit.html.haml
= render 'form', resource: @resource

app/views/admin/resources/index.html.haml
.divide-y.divide-gray-200.overflow-hidden.rounded-lg.bg-white.shadow
  .px-4.py-5.sm:px-6
    = render 'shared/header', title: t('admin.resources.title') do
      = render 'shared/button_new',  destination: new_admin_resource_path, title: t('admin.resources.newTitle'), data: { target: "_top" }
  .px-4.py-5.sm:p-6
    - if @resources.any?
      %table.mt-2.min-w-full.table-stripped
        %thead
          %tr
            %th{class: th_class.render}
            %th{class: th_class.render}
              = t 'admin.resources.name'
            %th{class: th_class.render(text_align: :right)}
              = t 'admin.resources.maxCapacity'
            %th{class: th_class.render}
        %tbody
          = render partial: 'admin/resources/resource', collection: @resources
    - else
      .mt-6
        = render 'shared/notification', {title: t('admin.resources.noResources')} do
          .mt-4
            .-mx-2.flex{class: "-my-1.5"}
              = link_to t('admin.resources.addFirst'), new_admin_resource_path, class: "px-2 py-1.5 rounded-md text-sm leading-5 font-medium text-blue-800 hover:bg-blue-100 focus:outline-none focus:bg-blue-100 transition ease-in-out duration-150", target: '_top'

app/views/admin/resources/new.html.haml
= render 'form', resource: @resource