config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :account, only: %i[show edit update]
    resources :custom_attributes
    resources :users
    resources :resources
    resources :schedule_categories
  end

  resources :bookings do
    collection do
      post :check
    end
  end

  resource :session
  resources :passwords, param: :token
  resources :calendar, only: %i[index new create] do
    collection do
      post :check
    end
  end
  resources :calendar_events, only: %i[index]

  root to: "calendar#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  attribute :role

  REGULAR = "regular".freeze
  ADMIN = "admin".freeze

  belongs_to :account

  has_many :bookings
  has_many :sessions, dependent: :destroy

  validates :name, presence: true
  validates :username, uniqueness: true, length: { in: 3..25 },
                       format: {
                         with: /\A[\p{L}\p{N}]+\z/,
                         message: :invalid
                       }
  validates :email, format: {
    with: /\A([\w+-].?)+@[a-z\d-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: :invalid
  }

  enum :role, { regular: 0, admin: 9 }

  before_save :downcase_attributes

  class << self
    def validate_reset_values(reset_token)
      User.where(reset_token:).where("reset_expires_at >= ?", Time.current).first
    end
  end

  def enable_reset_password
    self.reset_token = SecureRandom.hex(32)
    self.reset_expires_at = 4.hours.from_now
    save
  end

  def delete_reset_values
    self.reset_token = nil
    self.reset_expires_at = nil
    save
  end

  private

    def downcase_attributes
      self.username = username.downcase
      self.email = email&.downcase
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :find_user, only: %i[edit update destroy]

  def index
    @users = Current.account.users
  end

  def new
    @user = Current.account.users.new
  end

  def create
    @user = Current.account.users.create user_params

    if @user.save
      notice = t("admin.users.created")
      redirect_to admin_users_path, notice:
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      notice = t("admin.users.updated")
      redirect_to admin_users_path, notice:
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy

    notice = t("admin.users.deleted")

    redirect_to admin_users_path, notice:
  end

  private

    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :active)
    end

    def find_user
      @user = Current.account.users.find params[:id]
    end
end

app/views/admin/users/_form.html.haml
= render 'shared/form_card', title: t('admin.users.title') do
  = tw_form_with model: [:admin, user] do |form|
    = render 'shared/form_errors', errors: user.errors
    .space-y-1
      = form.text_input :name
      = form.text_input :username
      = form.text_input :email
      = form.text_input :password
    = render 'shared/form_actions', cancel_url: admin_users_path

app/views/admin/users/_user.html.haml
%tr
  %td{class: td_class.render}
    = link_to bookings_path(user_id: user.id), class: link_class.render do
      = user.name
  %td{class: td_class.render}
    = user.username
  %td{class: td_class.render}
    = user.email
  %td{class: td_class.render}
    .flex.gap-x-4.justify-end
      = render 'shared/button_edit', destination: edit_admin_user_path(user), data: {target: '_top'}
      = render 'shared/button_delete', destination: {model: [:admin, user]} 

app/views/admin/users/edit.html.haml
= render 'admin/users/form', user: @user

app/views/admin/users/index.html.haml
.divide-y.divide-gray-200.overflow-scroll.sm:overflow-hidden.rounded-lg.bg-white.shadow
  .px-4.py-5.sm:px-6
    = render 'shared/header', title: t('admin.users.title') do
      = render 'shared/button_new',  destination: new_admin_user_path, title: t('admin.users.newTitle'), data: { target: "_top" }
  .px-4.py-5.sm:p-6
    %table.mt-2.min-w-full.table-stripped
      %thead
        %tr
          %th{class: th_class.render}
            = t 'admin.users.name'
          %th{class: th_class.render}
            = t 'admin.users.username'
          %th{class: th_class.render}
            = t 'admin.users.email'
          %th{class: th_class.render}
      %tbody
        = render partial: 'admin/users/user', collection: @users

app/views/admin/users/new.html.haml
= render 'admin/users/form', user: @user